# Deep Learning Introduction
----

## 1. Introduction
- Deep learning is a machine learning technique that teaches computers to do what comes naturally to humans: `learn by example`
 ![image.png](https://github.com/rritec/datahexa/blob/master/images/Mentor_dl.jpg?raw=true)
 
 
- Most deep learning methods use **neural network** architectures, which is why deep learning models are often referred to as **deep neural networks**.
- The term “deep” usually refers to the number of hidden layers in the neural network. Traditional neural networks only contain 2-3 hidden layers, while deep networks can have as many as required.
- Deep learning models are trained by using large sets of labelled data and neural network architectures that learn features directly from the data without the need for manual feature extraction.
![nn](https://github.com/rritec/datahexa/blob/dev/images/dl/dl1.png?raw=true)

## 2. Examples of Deep Learning at Work
- Deep learning applications are used in industries from automated driving to medical devices.
- Automated Driving: Automotive researchers are using deep learning to automatically detect objects such as stop signs and traffic lights. In addition, deep learning is used to detect pedestrians, which helps decrease accidents.
- Aerospace and Defence: Deep learning is used to identify objects from satellites that locate areas of interest, and identify safe or unsafe zones for troops.
- Medical Research: Cancer researchers are using deep learning to automatically detect cancer cells. Teams at UCLA built an advanced microscope that yields a high-dimensional data set used to train a deep learning application to accurately identify cancer cells.
- Industrial Automation: Deep learning is helping to improve worker safety around heavy machinery by automatically detecting when people or objects are within an unsafe distance of machines.
- Electronics: Deep learning is being used in automated hearing and speech translation. For example, home assistance devices that respond to your voice and know your preferences are powered by deep learning applications.


## 3. Forward Propagation

![Forward Propagation](https://github.com/rritec/datahexa/blob/dev/images/dl/dl2.png?raw=true)

In [2]:
import numpy as np

In [3]:
input_np_array = np.array([2,3])

In [4]:
input_np_array

array([2, 3])

In [5]:
#define dict of weights
# randomly we will assign some weights
weights = {"node0":np.array([1,1]),
           "node1":np.array([-1,1]),
          "output_node":np.array([2,-1])}

In [6]:
weights

{'node0': array([1, 1]),
 'node1': array([-1,  1]),
 'output_node': array([ 2, -1])}

In [7]:
weights["node0"]

array([1, 1])

In [8]:
node0_value = (input_np_array * weights["node0"]).sum()

In [9]:
node0_value 

5

In [10]:
node1_value = (input_np_array * weights["node1"]).sum()

In [11]:
node1_value

1

In [12]:
hidden_layer = np.array([node0_value,node1_value])

In [13]:
hidden_layer

array([5, 1])

In [14]:
final_output = (hidden_layer * weights["output_node"]).sum()

In [15]:
final_output

9

## 4. Activation functions

- These are two types
    - Linear 
    - Non linear
![Forward Propagation](https://github.com/rritec/datahexa/blob/dev/images/dl/dl3.png?raw=true)
- The Main activate functions are
    - Linear Function
    - Sigmoid
    - Tanh
    - ReLu
    - Softmax
    
- [Must read 1](https://www.geeksforgeeks.org/activation-functions-neural-networks/)
- [Must read 2](https://medium.com/the-theory-of-everything/understanding-activation-functions-in-neural-networks-9491262884e0)


## 5. Apply Activation function to hidden node inputs to produce node output

In [1]:
import numpy as np

In [10]:
input_data = np.array([2, 3])
input_data

array([2, 3])

In [11]:
weights = {'node_0': np.array([1, 1]),
           'node_1': np.array([-1, 1]),
           'output': np.array([2, -1])}
weights

{'node_0': array([1, 1]), 'node_1': array([-1,  1]), 'output': array([ 2, -1])}

In [4]:
node_0_input = (input_data * weights['node_0']).sum()
node_0_input

5

In [5]:
node_0_output = np.tanh(node_0_input)
node_0_output

0.9999092042625951

In [6]:
node_1_input = (input_data * weights['node_1']).sum()
node_1_input

1

In [7]:
node_1_output = np.tanh(node_1_input)
node_1_output

0.7615941559557649

In [8]:
hidden_layer_output = np.array([node_0_output, node_1_output])
hidden_layer_output

array([0.9999092 , 0.76159416])

In [9]:
output = (hidden_layer_output * weights['output']).sum()
print(output)

1.2382242525694254


## 6. Deeper Network Using Activation Function as ReLu

- ReLU (Rectified Linear Activation).
![Forward Propagation](https://github.com/rritec/datahexa/blob/dev/images/dl/dl4.png?raw=true)

## 7. Multiple hidded layers 

![Forward Propagation](https://github.com/rritec/datahexa/blob/dev/images/dl/dl7.png?raw=true)

> How many hidden layers are available in above diagram?

In [12]:
import numpy as np
input_data = np.array([3, 5])
input_data

array([3, 5])

In [13]:

weights = {'node_0': np.array([2, 4]), 
           'node_1': np.array([4, -5]),
           'node_2': np.array([-1, 1]), 
           'node_3': np.array([2, 2]),
           'output': np.array([-3, 7])}
weights

{'node_0': array([2, 4]),
 'node_1': array([ 4, -5]),
 'node_2': array([-1,  1]),
 'node_3': array([2, 2]),
 'output': array([-3,  7])}

In [14]:
node_0_output = (input_data * weights['node_0']).sum()
print("node_0_output : ",node_0_output)
node_0_output_relu = np.maximum(node_0_output,0)
print("node_0_output_relu : ",node_0_output_relu)

node_0_output :  26
node_0_output_relu :  26


In [16]:
node_1_output = (input_data * weights['node_1']).sum()
print("node_1_output : ",node_1_output)
node_1_output_relu = np.maximum(node_1_output,0)
print("node_1_output_relu : ",node_1_output_relu)

node_1_output :  -13
node_1_output_relu :  0


In [18]:
hidden_layer1_output = np.array([node_0_output_relu, node_1_output_relu])
print("hidden_layer1_output : ",hidden_layer1_output)

hidden_layer1_output :  [26  0]


In [23]:
node_2_output = (hidden_layer1_output * weights['node_2']).sum()
print("node_2_output : ",node_2_output)
node_2_output_relu = np.maximum(node_2_output,0)
print("node_2_output_relu : ",node_2_output_relu)

node_2_output :  -26
node_2_output_relu :  0


In [24]:
node_3_output = (hidden_layer1_output * weights['node_3']).sum()
print("node_3_output : ",node_3_output)
node_3_output_relu = np.maximum(node_3_output,0)
print("node_3_output_relu : ",node_3_output_relu)

node_3_output :  52
node_3_output_relu :  52


In [25]:
hidden_layer2_output = np.array([node_2_output_relu, node_3_output_relu])
print("hidden_layer2_output : ",hidden_layer2_output)

hidden_layer2_output :  [ 0 52]


In [26]:
output = (hidden_layer2_output * weights['output']).sum()
print("output : ",output)
output_relu = np.maximum(output,0)
print("output_relu : ",output_relu)

output :  364
output_relu :  364


> Find more ways in implementing [relu function](https://stackoverflow.com/questions/32109319/how-to-implement-the-relu-function-in-numpy)
