# import required modules

In [39]:
import pandas as pd
from keras.utils import to_categorical

from keras.models import Sequential,load_model
from keras.layers import Dense

from IPython.display import SVG
from keras.utils.vis_utils import model_to_dot

# import data


## import training data

In [2]:
df = pd.read_csv("titanic_all_numeric_train.csv")
X_train=df.drop(labels=["survived"],axis=1).values
y_train=to_categorical(df.survived)
n_features=X_train.shape[1]
## importing test data
df = pd.read_csv("titanic_all_numeric_test.csv")
X_test=df.drop(labels=["survived"],axis=1).values
y_test=to_categorical(df.survived)

# Create NN architecture

In [54]:
def fun_get_model(arg1_n_features):
    model=Sequential()
    model.add(Dense(100,
               activation="relu",
               input_shape =(n_features,),
                name = "input_and_firsthidden_layer"))
    model.add(Dense(100,
               activation="relu",
               name = "second_hidden_layer"))
    model.add(Dense(2,
               activation="softmax"))
    return model

# SVG(data=model_to_dot(model, 
#                       show_shapes=True, 
#                       show_layer_names=True, rankdir='TB').create(prog='dot', format='svg'))

# compile the model

In [60]:
lr_to_test = [.00000001, 0.01, 1]
from keras.optimizers import SGD


In [62]:
for lr in lr_to_test:
    print(f"The model training with learning rate :{lr}")
    model=fun_get_model(n_features)
    my_optimizer = SGD(lr)
    model.compile(optimizer=my_optimizer,
                  loss="binary_crossentropy",
                  metrics=['accuracy'])
    model.fit(X_train,y_train,epochs=10)

The model training with learning rate :1e-08
Epoch 1/10
891/891 [==============================] - 2s 2ms/step - loss: 2.2097 - acc: 0.5196
Epoch 2/10
891/891 [==============================] - 0s 111us/step - loss: 2.2096 - acc: 0.5196
Epoch 3/10
891/891 [==============================] - 0s 100us/step - loss: 2.2095 - acc: 0.5196
Epoch 4/10
891/891 [==============================] - 0s 88us/step - loss: 2.2094 - acc: 0.5196
Epoch 5/10
891/891 [==============================] - 0s 129us/step - loss: 2.2094 - acc: 0.5196
Epoch 6/10
891/891 [==============================] - 0s 131us/step - loss: 2.2093 - acc: 0.5196
Epoch 7/10
891/891 [==============================] - 0s 160us/step - loss: 2.2093 - acc: 0.5196
Epoch 8/10
891/891 [==============================] - 0s 95us/step - loss: 2.2092 - acc: 0.5196
Epoch 9/10
891/891 [==============================] - 0s 177us/step - loss: 2.2091 - acc: 0.5196
Epoch 10/10
891/891 [==============================] - 0s 107us/step - loss: 2.2090 - 

# fit the model

In [33]:
#|model.fit?

In [34]:
model.fit(X_train,y_train,
          epochs=100)

W0222 08:17:31.020684 15248 deprecation_wrapper.py:119] From C:\Users\ramreddymyla\Anaconda3\envs\dl\lib\site-packages\keras\backend\tensorflow_backend.py:986: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.



Epoch 1/100
891/891 [==============================] - 1s 655us/step - loss: 3.0606 - acc: 0.5937
Epoch 2/100
891/891 [==============================] - 0s 144us/step - loss: 1.6636 - acc: 0.6173
Epoch 3/100
891/891 [==============================] - 0s 110us/step - loss: 1.1850 - acc: 0.6207
Epoch 4/100
891/891 [==============================] - 0s 167us/step - loss: 0.8086 - acc: 0.6521
Epoch 5/100
891/891 [==============================] - 0s 124us/step - loss: 0.6757 - acc: 0.6465
Epoch 6/100
891/891 [==============================] - 0s 171us/step - loss: 0.6339 - acc: 0.6914
Epoch 7/100
891/891 [==============================] - 0s 128us/step - loss: 0.5981 - acc: 0.6981
Epoch 8/100
891/891 [==============================] - 0s 123us/step - loss: 0.6028 - acc: 0.6992
Epoch 9/100
891/891 [==============================] - 0s 178us/step - loss: 0.5930 - acc: 0.7048 0s - loss: 0.5919 - acc: 0.707
Epoch 10/100
891/891 [==============================] - ETA: 0s - loss: 0.5786 - acc: 0

# save model

In [35]:
import os
os.chdir("C:/Users/ramreddymyla/Desktop/rritec/b20200222")

In [37]:
model.save("model_20200222.h5")

In [40]:
my_model = load_model('model_20200222.h5')

In [47]:
label_calculation=my_model.predict(X_test)[:,1]

In [52]:
my_model.predict(X_test)

array([[0.8156826 , 0.18431737],
       [0.1738516 , 0.82614833],
       [0.48516807, 0.5148319 ],
       [0.1720456 , 0.8279544 ],
       [0.77975225, 0.22024778],
       [0.7436762 , 0.2563238 ],
       [0.28999946, 0.7100005 ],
       [0.6862207 , 0.31377932],
       [0.41794658, 0.58205336],
       [0.28321847, 0.7167815 ],
       [0.43559104, 0.56440896],
       [0.25275996, 0.74724007],
       [0.74585295, 0.25414705],
       [0.6645046 , 0.33549544],
       [0.45372304, 0.5462769 ],
       [0.31982473, 0.6801753 ],
       [0.6192875 , 0.38071254],
       [0.7076203 , 0.29237974],
       [0.35134533, 0.64865476],
       [0.48405468, 0.5159453 ],
       [0.44820735, 0.5517927 ],
       [0.6219418 , 0.37805817],
       [0.3692601 , 0.6307399 ],
       [0.354624  , 0.6453759 ],
       [0.60653174, 0.39346826],
       [0.49075484, 0.50924516],
       [0.7610711 , 0.23892884],
       [0.28780308, 0.7121969 ],
       [0.47689933, 0.5231007 ],
       [0.8247751 , 0.17522492],
       [0.

In [48]:
label_calculation

array([0.18431737, 0.82614833, 0.5148319 , 0.8279544 , 0.22024778,
       0.2563238 , 0.7100005 , 0.31377932, 0.58205336, 0.7167815 ,
       0.56440896, 0.74724007, 0.25414705, 0.33549544, 0.5462769 ,
       0.6801753 , 0.38071254, 0.29237974, 0.64865476, 0.5159453 ,
       0.5517927 , 0.37805817, 0.6307399 , 0.6453759 , 0.39346826,
       0.50924516, 0.23892884, 0.7121969 , 0.5231007 , 0.17522492,
       0.6482462 , 0.7610002 , 0.5196695 , 0.2195544 , 0.75162804,
       0.68499905, 0.2390111 , 0.25207058, 0.54137206, 0.61109066,
       0.43841344, 0.6824675 , 0.25229827, 0.7041753 , 0.62374306,
       0.17763539, 0.31441644, 0.5196695 , 0.3610397 ], dtype=float32)

In [49]:
import numpy as np 
np.round(label_calculation)

array([0., 1., 1., 1., 0., 0., 1., 0., 1., 1., 1., 1., 0., 0., 1., 1., 0.,
       0., 1., 1., 1., 0., 1., 1., 0., 1., 0., 1., 1., 0., 1., 1., 1., 0.,
       1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 1., 0., 0., 1., 0.],
      dtype=float32)

In [51]:
df.survived

0     0
1     1
2     1
3     1
4     0
5     0
6     0
7     0
8     1
9     1
10    1
11    1
12    0
13    0
14    0
15    1
16    0
17    1
18    0
19    1
20    0
21    1
22    1
23    1
24    0
25    1
26    0
27    0
28    1
29    0
30    0
31    1
32    1
33    0
34    0
35    0
36    1
37    0
38    0
39    1
40    0
41    0
42    0
43    1
44    1
45    0
46    0
47    1
48    0
Name: survived, dtype: int64